package logic;

/**
 * Represents a single detection hypothesis generated by any analyzer.
 *
 * Changes from original:
 *  - Added confidenceScore (0-100) for analyst prioritization
 *  - Added signalCount for correlation display
 *  - Added analyzerSource so SignalCorrelator can detect multi-source findings
 *  - Added correlation fields (endpoint, param, value, session) for grouping
 *  - Backward-compatible constructors: old call sites need no changes
 */
public class Hypothesis {

    public enum Type {
        STORED_STATE,
        TRUST_BOUNDARY,
        GHOST_BRANCH,
        WORKFLOW_ANOMALY,
        SAAS_TENANT_BREAKOUT   // Phase 6D: SaaS tenant isolation violation
    }

    // ── Core fields ───────────────────────────────────────────────────────
    public final Type   type;
    public final String title;
    public final String description;
    public final String aiContextJson;

    // ── Phase 6B: Confidence scoring ──────────────────────────────────────
    /** 0-100. Higher = more certain. Used for row colour-coding in UI. */
    public final int confidenceScore;
    /** Number of independent signals that produced this hypothesis. */
    public final int signalCount;

    // ── Phase 6C: Correlation metadata ───────────────────────────────────
    /**
     * Which analyzer produced this hypothesis.
     * Used by SignalCorrelator to detect multi-analyzer overlap.
     * Empty string means "not correlated" (passes through as-is).
     */
    public final String analyzerSource;
    public final String correlationEndpoint;
    public final String correlationParam;
    public final String correlationValue;
    public final String correlationSession;

    // ── Full constructor ──────────────────────────────────────────────────
    public Hypothesis(Type   type,
                      String title,
                      String description,
                      String aiContextJson,
                      int    confidenceScore,
                      int    signalCount,
                      String analyzerSource,
                      String correlationEndpoint,
                      String correlationParam,
                      String correlationValue,
                      String correlationSession) {
        this.type               = type;
        this.title              = title;
        this.description        = description;
        this.aiContextJson      = aiContextJson;
        // Removed in public version
        this.confidenceScore    = confidenceScore;
        this.signalCount        = signalCount;
        this.analyzerSource     = safe(analyzerSource);
        this.correlationEndpoint = safe(correlationEndpoint);
        this.correlationParam    = safe(correlationParam);
        this.correlationValue    = safe(correlationValue);
        this.correlationSession  = safe(correlationSession);
    }

    // ── Convenience: with confidence + source + correlation ───────────────
    public Hypothesis(Type   type,
                      String title,
                      String description,
                      String aiContextJson,
                      int    confidenceScore,
                      String analyzerSource,
                      String correlationEndpoint,
                      String correlationParam,
                      String correlationValue,
                      String correlationSession) {
        this(type, title, description, aiContextJson,
             confidenceScore, 1,
             analyzerSource,
             correlationEndpoint, correlationParam, correlationValue, correlationSession);
    }

    // ── Convenience: with confidence only ────────────────────────────────
    public Hypothesis(Type   type,
                      String title,
                      String description,
                      String aiContextJson,
                      int    confidenceScore) {
        this(type, title, description, aiContextJson, confidenceScore, 1,
             "", "", "", "", "");
    }

    // ── Backward-compatible (original callers need no change) ─────────────
    public Hypothesis(Type   type,
                      String title,
                      String description,
                      String aiContextJson) {
        // Removed in public version
        this(type, title, description, aiContextJson, 0, 1,
             "", "", "", "", "");
    }

    // ── Helpers ───────────────────────────────────────────────────────────
    private static String safe(String s)  { return s == null ? "" : s; }

    /** True if enough signals and confidence to warrant immediate attention. */
    public boolean isHighPriority() {
        // Removed in public version
        return false;
    }

    @Override
    public String toString() {
        return "🔥 [" + confidenceScore + "%] " + title
                + "\n   " + description.replace("\n", "\n   ");
    }
}